---
title: "Dial in the model"
author: "Michael Koontz"
date: "4/24/2018"
output: html_document
---

```{r setup, message = FALSE}
library(lubridate)
library(sf)
library(lme4)
library(dplyr)
library(ggplot2)
library(here)
library(lubridate)
library(multcomp)
library(effects)
library(cowplot)
```

```{r read_files, message = FALSE}
fires <- st_read(dsn = here::here("/data/features/fire_perim/fire_perim_sn_16_1_shp/"),
                 stringsAsFactors = FALSE) %>% 
  st_transform(4326)
sn <- st_read(here::here("/data/features/SierraEcoregion_Jepson/SierraEcoregion_Jepson.shp")) %>% 
  st_transform(4326)

all_or_burned <- "burned"

if (all_or_burned == "all") {
  if (!file.exists(here::here("data/data_output/all-fire-samples_configured.rds"))) {
    source(here::here("data/data_carpentry/configure_fire-samples.R"))
  }
  ss <- readRDS(here::here("data/data_output/all-fire-samples_configured.rds"))
}

if (all_or_burned == "burned") {
  if (!file.exists(here::here("data/data_output/burned-fire-samples_configured.rds"))) {
      source(here::here("data/data_carpentry/configure_fire-samples.R"))
    }
    ss_burned <- readRDS(here::here("data/data_output/burned-fire-samples_configured.rds"))
}

```

## Modeling

What is it that we really care about? It's not 4-way interactions. What about including some 2-way interactions that we think might be important, along with the additive effects of "usual suspect" types of covariates, and leave it at that?

```{r simplify_models}
fm1 <- 
  glmer(stand_replacing ~ 
          het_ndvi_1_s +
          focal_mean_ndvi_1_s +
          preFire_ndvi_s +
          fm100_s +
          pahl_s + 
          topo_roughness_1_s + 
          focal_mean_ndvi_1_s:preFire_ndvi_s +
          het_ndvi_1_s:focal_mean_ndvi_1_s +
          het_ndvi_1_s:preFire_ndvi_s +
          het_ndvi_1_s:fm100_s +
          (1 | fire_id), 
        family = "binomial", 
        data = ss_burned, 
        control = glmerControl(optimizer = "bobyqa"))

fm2 <- 
  glmer(stand_replacing ~ 
          het_ndvi_2_s +
          focal_mean_ndvi_2_s +
          preFire_ndvi_s +
          fm100_s +
          pahl_s + 
          topo_roughness_2_s + 
          focal_mean_ndvi_2_s:preFire_ndvi_s +
          het_ndvi_2_s:focal_mean_ndvi_2_s +
          het_ndvi_2_s:preFire_ndvi_s +
          het_ndvi_2_s:fm100_s +
          (1 | fire_id), 
        family = "binomial", 
        data = ss_burned, 
        control = glmerControl(optimizer = "bobyqa"))

fm3 <- 
  glmer(stand_replacing ~ 
          het_ndvi_3_s +
          focal_mean_ndvi_3_s +
          preFire_ndvi_s +
          fm100_s +
          pahl_s + 
          topo_roughness_3_s + 
          focal_mean_ndvi_3_s:preFire_ndvi_s +
          het_ndvi_3_s:focal_mean_ndvi_3_s +
          het_ndvi_3_s:preFire_ndvi_s +
          het_ndvi_3_s:fm100_s +
          (1 | fire_id), 
        family = "binomial", 
        data = ss_burned, 
        control = glmerControl(optimizer = "bobyqa"))

fm4 <- 
  glmer(stand_replacing ~ 
          het_ndvi_4_s +
          focal_mean_ndvi_4_s +
          preFire_ndvi_s +
          fm100_s +
          pahl_s + 
          topo_roughness_4_s + 
          focal_mean_ndvi_4_s:preFire_ndvi_s +
          het_ndvi_4_s:focal_mean_ndvi_4_s +
          het_ndvi_4_s:preFire_ndvi_s +
          het_ndvi_4_s:fm100_s +
          (1 | fire_id), 
        family = "binomial", 
        data = ss_burned, 
        control = glmerControl(optimizer = "bobyqa"))

AIC(fm1, fm2, fm3, fm4)
summary(fm1)
```


```{r effects}

e_fm1 <- allEffects(fm1, 
                    xlevels = list(preFire_ndvi_s = seq(-2, 2, length.out = 17), 
                                   fm100_s = seq(-2, 2, length.out = 17), 
                                   focal_mean_ndvi_1_s = seq(-2, 2, length.out = 17), 
                                   het_ndvi_1_s = seq(-2, 2, length.out = 17),
                                   topo_roughness_1_s = seq(-2, 2, length.out = 17),
                                   pahl_s = seq(-2, 2, length.out = 17)))

e_fm1_topoRough <- as.data.frame(e_fm1[["topo_roughness_1_s"]])
e_fm1_pahl <- as.data.frame(e_fm1[["pahl_s"]])
e_fm1_het_neighborhoodMean <- as.data.frame(e_fm1[["het_ndvi_1_s:focal_mean_ndvi_1_s"]])
e_fm1_focalMean_neighborhoodMean <- as.data.frame(e_fm1[["focal_mean_ndvi_1_s:preFire_ndvi_s"]])
e_fm1_het_focalMean <- as.data.frame(e_fm1[["het_ndvi_1_s:preFire_ndvi_s"]])
e_fm1_het_fm100 <- as.data.frame(e_fm1[["het_ndvi_1_s:fm100_s"]])

# PrefireNDVI_ggplot
e_fm1_het_focalMean_subset <- 
  e_fm1_het_focalMean %>% 
  filter(het_ndvi_1_s == 0)

prefireNDVI_ggplot <-
  ggplot(e_fm1_het_focalMean_subset, aes(x = preFire_ndvi_s, y = fit, ymin = lower, ymax = upper)) +
  geom_line(lwd = 1.25) +
  geom_ribbon(alpha = 0.4) +
  xlab(label = "Prefire vegetation density") +
  ylab(label = "") +
  theme(text = element_text(size = 28),
        axis.title.x = element_text(margin = margin(t = 28, b = 28, l = 0, r = 0)),
        axis.title.y = element_text(margin = margin(t = 0, b = 0, l = 28, r = 28)),
        axis.text.x = element_text(size = 28),
        axis.text.y = element_text(size = 28))
prefireNDVI_ggplot

# fm100 effect
e_fm1_fm100 <- 
  e_fm1_het_fm100 %>% 
  filter(het_ndvi_1_s == 0)

fm100_ggplot <- 
  ggplot(e_fm1_fm100, aes(x = fm100_s, y = fit, ymin = lower, ymax = upper)) +
  geom_line(lwd = 1.25) + 
  geom_ribbon(alpha = 0.4) +
  xlab(label = "Fuel moisture") +
  ylab(label = "") +
  theme(text = element_text(size = 28),
        axis.title.x = element_text(margin = margin(t = 28, b = 28, l = 0, r = 0)),
        axis.title.y = element_text(margin = margin(t = 0, b = 0, l = 28, r = 28)),
        axis.text.x = element_text(size = 28),
        axis.text.y = element_text(size = 28))
fm100_ggplot

# topo roughness effect
topo_rough_ggplot <- 
  ggplot(e_fm1_topoRough, aes(x = topo_roughness_1_s, y = fit, ymin = lower, ymax = upper)) +
  geom_line(lwd = 1.25) + 
  geom_ribbon(alpha = 0.4) +
  xlab(label = "Topographic roughness") +
  ylab(label = "") +
  theme(text = element_text(size = 28),
        axis.title.x = element_text(margin = margin(t = 28, b = 28, l = 0, r = 0)),
        axis.title.y = element_text(margin = margin(t = 0, b = 0, l = 28, r = 28)),
        axis.text.x = element_text(size = 28),
        axis.text.y = element_text(size = 28))
topo_rough_ggplot

# pahl effect
pahl_ggplot <- 
  ggplot(e_fm1_pahl, aes(x = pahl_s, y = fit, ymin = lower, ymax = upper)) +
  geom_line(lwd = 1.25) + 
  geom_ribbon(alpha = 0.4) +
  xlab(label = "Annual heat load") +
  ylab(label = "") +
  theme(text = element_text(size = 28),
        axis.title.x = element_text(margin = margin(t = 28, b = 28, l = 0, r = 0)),
        axis.title.y = element_text(margin = margin(t = 0, b = 0, l = 28, r = 28)),
        axis.text.x = element_text(size = 28),
        axis.text.y = element_text(size = 28))
pahl_ggplot

panel_plot <- plot_grid(NULL, prefireNDVI_ggplot, fm100_ggplot, NULL, pahl_ggplot, topo_rough_ggplot, ncol=3, nrow = 2, rel_widths = c(0.2, 1, 1))

panel_plot_labelled <- 
  panel_plot + 
  draw_label(label = "Probability of\n90%\ntree mortality", x = 0.08, angle = 0, size = 28)

panel_plot_labelled
# ggplot2::ggsave(plot = panel_plot_labelled, filename = "~/dev/presentations/2018-08-09_esa2018-new-orleans-louisiana/usual-suspects.png", device = "png", width = 15)

# heterogeneity interacting with fuel moisture effect (not quite significant)
e_fm1_het_fm100_subset <-
  e_fm1_het_fm100 %>% 
  filter(fm100_s %in% c(-2, 0, 2))
         
het_fm100_ggplot <- 
  ggplot(e_fm1_het_fm100_subset, aes(x = het_ndvi_1_s, y = fit, ymin = lower, ymax = upper, color = as.factor(fm100_s), fill = as.factor(fm100_s))) +
  geom_line(lwd = 1.25) + 
  geom_ribbon(alpha = 0.4) +
  xlab(label = "Neighborhood variability (scaled)") +
  ylab(label = "") +
  scale_color_viridis_d(name = "Fuel moisture (scaled)") +
  scale_fill_viridis_d(name = "Fuel moisture (scaled)") +
  theme(text = element_text(size = 28),
        axis.title.x = element_text(margin = margin(t = 28, b = 28, l = 0, r = 0)),
        axis.title.y = element_text(margin = margin(t = 0, b = 0, l = 28, r = 28)),
        axis.text.x = element_text(size = 28),
        axis.text.y = element_text(size = 28))
het_fm100_ggplot

# focal mean interacting with neighborhood mean effect  (strong interaction; accounting variable, so not interpretting biologically)
# these covariates are super colinear, though there is some information gained by including them both
# Some of the covariate space just doesn't exist in real life (high focal mean, low neighborhood mean and vice versa; so no real sense in making predictions in those areas)
e_fm1_focalMean_neighborhoodMean_subset <-
  e_fm1_focalMean_neighborhoodMean %>% 
  filter(focal_mean_ndvi_1_s %in% c(-2, 0, 2))

e_fm1_focalMean_neighborhoodMean_ggplot <-
  ggplot(e_fm1_focalMean_neighborhoodMean_subset, aes(x = preFire_ndvi_s, y = fit, ymin = lower, ymax = upper, color = as.factor(focal_mean_ndvi_1_s), fill = as.factor(focal_mean_ndvi_1_s))) +
  geom_line(lwd = 1.25) + 
  geom_ribbon(alpha = 0.4) +
  scale_fill_viridis_d(name = "Neighborhood NDVI (scaled)") +
  scale_color_viridis_d(name = "Neighborhood NDVI (scaled)") +
  xlab(label = "Prefire vegetation density (scaled)") +
  ylab(label = "Probability of 90% tree mortality") +
  theme(text = element_text(size = 28),
        axis.title.x = element_text(margin = margin(t = 28, b = 28, l = 0, r = 0)),
        axis.title.y = element_text(margin = margin(t = 0, b = 0, l = 28, r = 28)),
        axis.text.x = element_text(size = 28),
        axis.text.y = element_text(size = 28))

e_fm1_focalMean_neighborhoodMean_ggplot

# focal mean interacting with neighborhood mean effect
e_fm1_focalMean_neighborhoodMean_subset_2 <-
  e_fm1_focalMean_neighborhoodMean %>% 
  filter(preFire_ndvi_s %in% c(-2, 0, 2))

e_fm1_focalMean_neighborhoodMean_ggplot_2 <-
  ggplot(e_fm1_focalMean_neighborhoodMean_subset_2, aes(x = focal_mean_ndvi_1_s, y = fit, ymin = lower, ymax = upper, color = as.factor(preFire_ndvi_s), fill = as.factor(preFire_ndvi_s))) +
  geom_line(lwd = 1.25) + 
  geom_ribbon(alpha = 0.4) +
  scale_fill_viridis_d(name = "Prefire NDVI (scaled)") +
  scale_color_viridis_d(name = "Prefire NDVI (scaled)") +
  xlab(label = "Neighborhood NDVI (scaled)") +
  ylab(label = "Probability of 90% tree mortality") +
  theme(text = element_text(size = 28),
        axis.title.x = element_text(margin = margin(t = 28, b = 28, l = 0, r = 0)),
        axis.title.y = element_text(margin = margin(t = 0, b = 0, l = 28, r = 28)),
        axis.text.x = element_text(size = 28),
        axis.text.y = element_text(size = 28))

e_fm1_focalMean_neighborhoodMean_ggplot_2

# ggplot2::ggsave(plot = e_fm1_focalMean_neighborhoodMean_ggplot, filename = "~/dev/presentations/2018-08-09_esa2018-new-orleans-louisiana/focalMean_neighborhoodMean.png", device = "png")

# Heterogeneity main effect
het_effect_gg <- 
  e_fm1_het_focalMean %>% 
  filter(preFire_ndvi_s == 0)

het_effect_ggplot <-
  ggplot(het_effect_gg, aes(x = het_ndvi_1_s, y = fit, ymin = lower, ymax = upper)) +
  geom_line(lwd = 1.25) +
  geom_ribbon(alpha = 0.4) +
  ylab(label = "Probability of 90% tree mortality") +
  xlab(label = "Neighborhood forest variability (scaled)\n(90m x 90m window)") +
  theme(text = element_text(size = 28),
        axis.text.x = element_text(size = 28, margin = margin(t = 14, b = 14, l = 0, r = 0)),
        axis.text.y = element_text(size = 28, margin = margin(t = 0, b = 0, l = 14, r = 14)),
        axis.title.x = element_text(margin = margin(t = 28, b = 28, l = 0, r = 0)),
        axis.title.y = element_text(margin = margin(t = 0, b = 0, l = 28, r = 28)))
het_effect_ggplot
```